name: Setup Monorepo
description: Prepare and install everything for the monorepo

inputs:
  node-version:
    description: Version of Node to use
    default: 18.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: 🏗 Setup Supabase
      uses: supabase/setup-cli@v1
      with:
        version: ${{ inputs.supabase-version }}

    - name: 📦 Install packages
      run: yarn install --frozen-lockfile
