const app = "/x";

export const path = {
  to: {
    accounting: `${app}/accounting`,
    accountingCategoryList: (id: string) =>
      `${app}/accounting/categories/list/${id}`,
    accountingCategories: `${app}/accounting/categories`,
    accountingDefaults: `${app}/accounting/defaults`,
    chartOfAccounts: `${app}/accounting/charts`,
    currencies: `${app}/accounting/currencies`,
    customer: (id: string) => `${app}/customer/${id}`,
    customers: `${app}/sales/customers`,
    customerContacts: (id: string) => `${app}/customer/${id}/contacts`,
    customerLocations: (id: string) => `${app}/customer/${id}/locations`,
    documents: `${app}/documents/search`,
    documentsTrash: `${app}/documents/search?q=trash`,
    fiscalYears: `${app}/accounting/years`,
    forgotPassword: "/forgot-password",
    home: app,
    inventory: `${app}/inventory`,
    invoicing: `${app}/invoicing`,
    newCustomer: `${app}/customer/new`,
    newPart: `${app}/part/new`,
    newPurchaseInvoice: `${app}/purchase-invoice/new`,
    newPurchaseOrder: `${app}/purchase-order/new`,
    newSupplier: `${app}/supplier/new`,
    part: (id: string) => `${app}/part/${id}`,
    partCosting: (id: string) => `${app}/part/${id}/costing`,
    partGroups: `${app}/parts/groups`,
    partInventory: (id: string) => `${app}/part/${id}/inventory`,
    partInventoryLocation: (id: string, locationId: string) =>
      `${app}/part/${id}/inventory?location=${locationId}`,
    partManufacturing: (id: string) => `${app}/part/${id}/manufacturing`,
    partPlanning: (id: string) => `${app}/part/${id}/planning`,
    partPlanningLocation: (id: string, locationId: string) =>
      `${app}/part/${id}/planning?location=${locationId}`,
    partPricing: (id: string) => `${app}/part/${id}/pricing`,
    partPurchasing: (id: string) => `${app}/part/${id}/purchasing`,
    partSalePrice: (id: string) => `${app}/part/${id}/sale-price`,
    partSuppliers: (id: string) => `${app}/part/${id}/suppliers`,
    parts: `${app}/parts`,
    partsSearch: `${app}/parts/search`,
    paymentTerms: `${app}/accounting/payment-terms`,
    profile: `${app}/account/profile`,
    purchaseInvoice: (id: string) => `${app}/purchase-invoice/${id}`,
    purchaseInvoiceDetails: (id: string) =>
      `${app}/purchase-invoice/${id}/details`,
    purchaseInvoices: `${app}/invoicing/purchasing`,
    purchaseOrder: (id: string) => `${app}/purchase-order/${id}`,
    purchaseOrderDelivery: (id: string) =>
      `${app}/purchase-order/${id}/delivery`,
    purchaseOrderDetails: (id: string) => `${app}/purchase-order/${id}/details`,
    purchaseOrderPayment: (id: string) => `${app}/purchase-order/${id}/payment`,
    purchaseOrders: `${app}/purchasing/orders`,
    purchasing: `${app}/purchasing`,
    receipt: (id: string) => `${app}/inventory/receipt/${id}`,
    receipts: `${app}/inventory/receipts`,
    resetPassord: "/reset-password",
    root: "/",
    shippingMethods: `${app}/inventory/shipping-methods`,
    supplier: (id: string) => `${app}/supplier/${id}`,
    suppliers: `${app}/purchasing/suppliers`,
    supplierContacts: (id: string) => `${app}/supplier/${id}/contacts`,
    supplierLocations: (id: string) => `${app}/supplier/${id}/locations`,
    supplierTypes: `${app}/purchasing/supplier-types`,
    uom: `${app}/parts/uom`,
  },
} as const;
