const app = "/x";

export const path = {
  to: {
    abilities: `${app}/resources/abilities`,
    ability: (id: string) => `${app}/resources/ability/${id}`,
    accounting: `${app}/accounting`,
    accountingCategoryList: (id: string) =>
      `${app}/accounting/categories/list/${id}`,
    accountingCategories: `${app}/accounting/categories`,
    accountingDefaults: `${app}/accounting/defaults`,
    attributes: `${app}/resources/attributes`,
    attributeCategoryList: (id: string) =>
      `${app}/resources/attributes/list/${id}`,
    chartOfAccounts: `${app}/accounting/charts`,
    contractors: `${app}/resources/contractors`,
    currencies: `${app}/accounting/currencies`,
    customer: (id: string) => `${app}/customer/${id}`,
    customers: `${app}/sales/customers`,
    customerAccounts: `${app}/users/customers`,
    customerContacts: (id: string) => `${app}/customer/${id}/contacts`,
    customerLocations: (id: string) => `${app}/customer/${id}/locations`,
    customerTypes: `${app}/sales/customer-types`,
    departments: `${app}/resources/departments`,
    documents: `${app}/documents/search`,
    documentsTrash: `${app}/documents/search?q=trash`,
    employeeAccounts: `${app}/users/employees`,
    employeeTypes: `${app}/users/employee-types`,
    equipment: `${app}/resources/equipment`,
    equipmentTypeList: (id: string) => `${app}/resources/equipment/list/${id}`,
    fiscalYears: `${app}/accounting/years`,
    forgotPassword: "/forgot-password",
    groups: `${app}/users/groups`,
    holidays: `${app}/resources/holidays`,
    home: app,
    inventory: `${app}/inventory`,
    invoicing: `${app}/invoicing`,
    locations: `${app}/resources/locations`,
    login: "/login",
    newCustomer: `${app}/customer/new`,
    newPart: `${app}/part/new`,
    newPurchaseInvoice: `${app}/purchase-invoice/new`,
    newPurchaseOrder: `${app}/purchase-order/new`,
    newSupplier: `${app}/supplier/new`,
    part: (id: string) => `${app}/part/${id}`,
    partCosting: (id: string) => `${app}/part/${id}/costing`,
    partGroups: `${app}/parts/groups`,
    partInventory: (id: string) => `${app}/part/${id}/inventory`,
    partInventoryLocation: (id: string, locationId: string) =>
      `${app}/part/${id}/inventory?location=${locationId}`,
    partManufacturing: (id: string) => `${app}/part/${id}/manufacturing`,
    partPlanning: (id: string) => `${app}/part/${id}/planning`,
    partPlanningLocation: (id: string, locationId: string) =>
      `${app}/part/${id}/planning?location=${locationId}`,
    partPricing: (id: string) => `${app}/part/${id}/pricing`,
    partPurchasing: (id: string) => `${app}/part/${id}/purchasing`,
    partSalePrice: (id: string) => `${app}/part/${id}/sale-price`,
    partSuppliers: (id: string) => `${app}/part/${id}/suppliers`,
    parts: `${app}/parts`,
    partsSearch: `${app}/parts/search`,
    partners: `${app}/resources/partners`,
    paymentTerms: `${app}/accounting/payment-terms`,
    people: `${app}/resources/people`,
    profile: `${app}/account/profile`,
    purchaseInvoice: (id: string) => `${app}/purchase-invoice/${id}`,
    purchaseInvoiceDetails: (id: string) =>
      `${app}/purchase-invoice/${id}/details`,
    purchaseInvoices: `${app}/invoicing/purchasing`,
    purchaseOrder: (id: string) => `${app}/purchase-order/${id}`,
    purchaseOrderDelivery: (id: string) =>
      `${app}/purchase-order/${id}/delivery`,
    purchaseOrderDetails: (id: string) => `${app}/purchase-order/${id}/details`,
    purchaseOrderPayment: (id: string) => `${app}/purchase-order/${id}/payment`,
    purchaseOrders: `${app}/purchasing/orders`,
    purchasing: `${app}/purchasing`,
    receipt: (id: string) => `${app}/inventory/receipt/${id}`,
    receipts: `${app}/inventory/receipts`,
    resetPassord: "/reset-password",
    resources: `${app}/resources`,
    root: "/",
    sales: `${app}/sales`,
    sequences: `${app}/settings/sequences`,
    shifts: `${app}/resources/shifts`,
    shippingMethods: `${app}/inventory/shipping-methods`,
    supplier: (id: string) => `${app}/supplier/${id}`,
    suppliers: `${app}/purchasing/suppliers`,
    supplierAccounts: `${app}/users/suppliers`,
    supplierContacts: (id: string) => `${app}/supplier/${id}/contacts`,
    supplierLocations: (id: string) => `${app}/supplier/${id}/locations`,
    supplierTypes: `${app}/purchasing/supplier-types`,
    uom: `${app}/parts/uom`,
    users: `${app}/users`,
    workCells: `${app}/resources/work-cells`,
    workCellTypeList: (id: string) => `/${app}/resources/work-cells/list/${id}`,
  },
} as const;
